### PR TITLE
Amazon aws-sdk-php v3 compatibility

### PR DESCRIPTION
**Pull request by leandrogehlen**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Tests pass?   | ✔️

### CODE REVIEW

**Comment by phrakon** [comment]
I think it would be better to store your feature under amazon3 folder which stores copied and refactored files from original amazon storage and bucket classes. It will not break BC.

**Comment by klimov-paul** [comment]
Relates #18

As [I already said](https://github.com/yii2tech/file-storage/issues/16#issuecomment-409929515), I am unable to verify or accept any changes to Amazon support code, since I do not have access to S3 service anymore.
If you create a PR for SDK 3.0 support, you will have to wait until other people confirm it is correct, or until I will obtain access for Amazon S3 service from some source.

@phrakon, can you confirm this patch is functional?

> I think it would be better to store your feature under amazon3 folder which stores copied and refactored files from original amazon storage and bucket classes. It will not break BC.

I do not think it is necessary, if changeset will be accepted, it will be released as `1.2.0` version.

**Comment by phrakon** [comment]
@klimov-paul, don't know. I implemented owned similar extension for yandex cloud s3 (it is compatible with amazon). It looks like the pull request, but has another things - region, endpoint. So, do not confirm, did not tested.

**Comment by rhertogh** [comment]
@klimov-paul You can simulate AWS S3 locally with https://github.com/localstack/localstack

docker-compose.yml
```yaml
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8081:8080"
    environment:
      - SERVICES=s3
      - USE_SSL=false
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
```

yii config
```php
$config = [
   'components' =>
        'fileStorage' => [
            'class' => yii2tech\filestorage\amazon\Storage::class,
            'amazonS3Config' => [
                'endpoint' => 'http://localhost:4566', # if you're running yii also in a docker container make sure it's on the same network as the localstack container and use 'http://localstack:4566' here.
                'use_path_style_endpoint' => true,
            ],
            'buckets' => [
                'images' => [
                    'region' => 'eu-central-1',
                ],
            ],
        ],
   ],
];
```

The code in this PR does not work with the new aws/aws-sdk-php (tested with version 3.147.14). The initialization of the S3Client fails in src/amazon/Storage.php(122). It's missing a '[version](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#cfg-version)' and '[region](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#cfg-region)'.
I think that it therefore would be best to move the creation of the S3Client form the `Storage` to the `Bucket` class so that they can be configured and cached independently (different buckets can be in different regions).

@leandrogehlen Are you interested in updating this PR? Otherwise I'll create a new one

**Comment by leandrogehlen** [comment]
I'am using in production this PR 

The configuration bellow works fine for me
```php
...
'storage' => [
    'class' => 'yii2tech\filestorage\amazon\Storage',
    'awsKey' => getenv('S3_KEY'),
    'awsSecretKey' => getenv('S3_SECRET'),
    'buckets' => [
        'pedido-producao' => [
            'acl' => 'private'
        ],
        'pedido-desenv' => [
            'acl' => 'private'
        ]
    ]
],
```

**Comment by rhertogh** [comment]
> I'am using in production this PR

Which version of the SDK are you using? According to the documentation (https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html) version 'version' and 'region' are required.
Without those fields the SDK fails to create the client, by adding them the code in the PR works.

**Comment by leandrogehlen** [comment]
@rhertogh sdk version: `"aws/aws-sdk-php": "^3.151.0"`

**Comment by leandrogehlen** [comment]
Feel free to make the necessary changes

**Comment by rhertogh** [comment]
@leandrogehlen I've updated the SDK to v3.170.0 but the error still occurs.
What do line 77-88 say in your vendor/aws/aws-sdk-php/src/ClientResolver.php class?
mine state:
```
        'region' => [
            'type'     => 'value',
            'valid'    => ['string'],
            'required' => [__CLASS__, '_missing_region'],
            'doc'      => 'Region to connect to. See http://docs.aws.amazon.com/general/latest/gr/rande.html for a list of available regions.',
        ],
        'version' => [
            'type'     => 'value',
            'valid'    => ['string'],
            'required' => [__CLASS__, '_missing_version'],
            'doc'      => 'The version of the webservice to utilize (e.g., 2006-03-01).',
        ],
```
indicating the 'required' attribute.

**Comment by leandrogehlen** [comment]
Closed in favor #25

**Pull request closed without merging**
